### PR TITLE
fixes #3 #5 #6 #7 #10

### LINKED ISSUE #3: Display the number of members in each group in a neat table.
The program currently prints a list with the number of members in each group.

Make it display a table with name of group and number of members in group.

### LINKED ISSUE #6: fix: complete Xpath of the element that contains number of participants.
Complete the Xpath in line 43 of auto.py

### PR DESCRIPTION
**Pull request by ssaakaash**
### #5
Added requirements.py file which spawns a subprocess to call pip install on each dependency listed in requirements.txt (which I deem needed as having the requirements in the python file which also has code isn't good practice)

### #6 
Added xpath to the number of members in group element

### #7 
Added a file `install_driver.py` which runs while installing requirements, asking the user for their platform, getting the current stable chrome version, downloading the chromedriver into the current directory and extracting it. Also sets the CHROME_DRIVER_PATH since it is now known.

### #10 
Removed groupname by getting the x element and clicking it after each search.

### #3 
It prints the group name and number of participants in tabular form using tabulate

### CODE REVIEW

**Comment by joel2607** [comment]
Kindly send each commit as a separate pull request in response to each issue.

since you have fixed 4 issues, you can send your pull request from those issues itself. so kindly send the changes as a pull request over there.

**Comment by joel2607** [comment]
Amazing work!! Can you resolve the merge conficts in this Pull Request?

**Comment by ssaakaash** [comment]
Hi how do I resolve the merge conflicts?
Could you open the PR so I could do that, or should I send a new PR?

**Comment by joel2607** [comment]
Im opening the PR, just add your commits to this further.

**Pull request closed without merging**
